### ISSUE TITLE
Type mismatch is xdmp.login -- null is not assignable to undefined

### ISSUE THREAD

**Issue by sjordan1975** [grtjn/marklogic-typescript-definitions#18]
Given the following:
xdmp.login("username", null, true, ["sa-librarian"])

Typescript validator complains:
Argument of type 'null' is not assignable to parameter of type 'string|undefined'

xdmp.login documentation: https://docs.marklogic.com/xdmp.login
xdmp.login("username", null)

**Comment by grtjn** [comment]
@christyharagan, what would you make of this?

**Comment by christyharagan** [comment]
Aha, this is new typing in TypeScript 2 onwards. It does a great job of disambiguating ```null``` and ```undefined``` values.

In this case, the xdmp.login function will have a signature:
 ```ts
(username:string, password?:string)
``` 

Where the ```?``` means "optional" and essentially translates to the type: ```string|undefined```.

TypeScript treats ```null``` and ```undefined``` as different values (as it should), thus the typing error.

As the current typings work, the correct usage this function is either:

```ts
xdmp.login("username")

// OR

xdmp.login("username", undefined)
```

If passing in ```null``` to this method is a common pattern, we could alter the typing appropriately. Happy to take suggestions on this.

**Comment by grtjn** [comment]
The docs (as referenced by OP) talk about null, not undefined, but perhaps both actually works? Using null here makes more sense to me personally too..

**Comment by rickypowell** [comment]
So if we mark the function parameters as follows, we can accommodate both usages and avoid breaking interfaces.
```
(username:string, password?:string|null|undefined)
```

**Comment by grtjn** [comment]
That last comment was helpful, including this in the mL9 release..
